APP_NAME = "Sirius AI Tray Assistant"
APP_SLUG = "Sirius_AI_Tray_Assistant"
APP_VERSION = "3.6.0"
APP_PUBLISHER = "zoott28354"
APP_URL = "https://github.com/zoott28354/sirius-ai-tray-assistant"
APP_COPYRIGHT = "Copyright (c) 2026 zoott28354"
APP_LICENSE = "GNU GPL v3 or later"
